### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.iekie.free.clean-1/base.apk"],nativeLibraryDirectories=[/data/app/com.iekie.free.clean-1/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libun7zip.so"

### ISSUE THREAD

**Issue by jhwsx** [hzy3774/AndroidUn7zip#16]
# 1. 基本信息：
- as 版本：3.3.2
- gradle 版本：3.3.2
- gradle 插件版本：4.10.1
- compileSdkVersion：28
- targetSdkVersion：28
- un7zip_version：1.5.0
# 2. 错误信息：
- 机型：vivo X9
- 系统版本：6.0.1
- 错误日志：
```text
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file &quot;/data/app/com.iekie.free.clean-1/base.apk&quot;],nativeLibraryDirectories=[/data/app/com.iekie.free.clean-1/lib/x86, /vendor/lib, /system/lib]]] couldn&#39;t find &quot;libun7zip.so&quot;
	at java.lang.Runtime.loadLibrary(Runtime.java:369)
	at java.lang.System.loadLibrary(System.java:1077)
	at com.hzy.lib7z.Z7Extractor.&lt;clinit&gt;(Unknown Source)
	at org.clean.library.c.a.b(Unknown Source)
	at org.clean.library.c$1.run(Unknown Source)
	at com.iekie.a.a.g.d$a.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
```
# 3. 代码使用：
没有在 build.gradle 文件中过滤 so。

**Comment by jhwsx** [comment]
这个问题，同时反馈给了 vivo 那边，毕竟现在是机型集中。

**Comment by huzongyao** [comment]
尝试编译源码看看，可能是没有x86的库
